export interface Resource {
  id: string;
  title: string;
  category: string;
  tags: string[];
  summary: string;
  sourceFile?: string;
  type: "document" | "spreadsheet" | "pdf" | "template" | "guide";
}

export const CATEGORIES = [
  "Product Knowledge",
  "Carrier Profiles",
  "Investment Universe",
  "Compliance References",
  "Partner Guides",
  "Process Documents",
  "Templates",
  "Case Materials",
  "Fee Structures",
];

export const RESOURCES: Resource[] = [
  // Product Knowledge
  {
    id: "ppva-overview",
    title: "PPVA Overview",
    category: "Product Knowledge",
    tags: ["ppva", "overview", "product", "annuity"],
    summary: "Comprehensive overview of Private Placement Variable Annuity structure, benefits, and mechanics.",
    sourceFile: "docs/PPVA Overview - July 2024.pdf",
    type: "pdf",
  },
  {
    id: "ppli-basics",
    title: "PPLI Basics",
    category: "Product Knowledge",
    tags: ["ppli", "basics", "education", "insurance"],
    summary: "Foundational education on Private Placement Life Insurance — structure, tax benefits, and use cases.",
    sourceFile: "docs/PPLI basic.pdf",
    type: "pdf",
  },
  {
    id: "ppva-vs-ppli",
    title: "PPVA vs PPLI Comparison",
    category: "Product Knowledge",
    tags: ["ppva", "ppli", "comparison", "differences"],
    summary: "Side-by-side comparison of PPVA and PPLI structures, highlighting when each is appropriate.",
    type: "guide",
  },
  {
    id: "current-build",
    title: "Current Build — Private Placement at TPBC",
    category: "Product Knowledge",
    tags: ["tpbc", "positioning", "platform", "current"],
    summary: "TPBC's current positioning and institutional-grade planning structure for private placement.",
    sourceFile: "docs/Current-Build-Private-Placement-at-TPBC-Building-Institutional-Grade-Planning-Structures.pdf",
    type: "pdf",
  },
  // Carrier Profiles
  {
    id: "advantage-alpr",
    title: "Advantage Life Puerto Rico (ALPR)",
    category: "Carrier Profiles",
    tags: ["advantage", "alpr", "carrier", "primary"],
    summary: "Primary carrier profile — Advantage Life Puerto Rico. Fee structure, process, entity architecture, and compliance framework.",
    type: "guide",
  },
  {
    id: "axcelus-factsheet",
    title: "Axcelus Financial Fact Sheet",
    category: "Carrier Profiles",
    tags: ["axcelus", "factsheet", "carrier"],
    summary: "Axcelus Financial fact sheet with carrier background, capabilities, and product overview.",
    sourceFile: "docs/Axcelus Financial Fact Sheet - July 2024.pdf",
    type: "pdf",
  },
  {
    id: "lombard-guidelines",
    title: "Lombard PPLI Underwriting Guidelines",
    category: "Carrier Profiles",
    tags: ["lombard", "underwriting", "guidelines"],
    summary: "Lombard International underwriting guidelines for PPLI placement.",
    sourceFile: "docs/Lombard PPLI Underwriting Guidelines.docx",
    type: "document",
  },
  // Investment Universe
  {
    id: "sali-options",
    title: "SALI Investment Options and Overview",
    category: "Investment Universe",
    tags: ["sali", "investments", "funds", "managers"],
    summary: "Comprehensive list of ~80 investment managers and fund options available through SALI for private placement.",
    sourceFile: "docs/SALI Investment Options and Overview (1).xlsx",
    type: "spreadsheet",
  },
  {
    id: "portfolio-proposal",
    title: "Detailed Portfolio Proposal (Advantage)",
    category: "Investment Universe",
    tags: ["portfolio", "proposal", "advantage", "performance"],
    summary: "Detailed portfolio proposal with Crystal Funds performance data and allocation frameworks.",
    sourceFile: "docs/Detailed Portfolio Proposal (Advantage Insurance).pdf",
    type: "pdf",
  },
  // Compliance References
  {
    id: "817h-rules",
    title: "IRC 817(h) Diversification Rules",
    category: "Compliance References",
    tags: ["817h", "diversification", "compliance", "irs"],
    summary: "Detailed explanation of IRC 817(h) diversification requirements — the 5 rules that must be maintained at all times.",
    type: "guide",
  },
  {
    id: "investor-control",
    title: "Investor Control Doctrine",
    category: "Compliance References",
    tags: ["investor-control", "compliance", "doctrine"],
    summary: "Comprehensive guide to the investor control doctrine — what clients can and cannot do regarding investment decisions.",
    type: "guide",
  },
  {
    id: "bd-ria-separation",
    title: "BD/RIA Separation Guidelines",
    category: "Compliance References",
    tags: ["bd", "ria", "separation", "compliance", "fiduciary"],
    summary: "Strict temporal separation rules between broker-dealer and RIA phases. Key compliance framework for PPVA placement.",
    type: "guide",
  },
  {
    id: "underwriting-guidance",
    title: "International PPVA Underwriting Guidance",
    category: "Compliance References",
    tags: ["underwriting", "international", "eligibility"],
    summary: "Carrier eligibility matrix based on client nationality, residency, and entity type.",
    sourceFile: "source-data/International PPVA Underwriting Guidance as of July 2020 (1).xlsx",
    type: "spreadsheet",
  },
  // Partner Guides
  {
    id: "ria-guide",
    title: "RIA Partner Guide",
    category: "Partner Guides",
    tags: ["ria", "partner", "guide", "fiduciary"],
    summary: "How RIAs participate in PPVA cases — from engagement through ongoing portfolio management.",
    type: "guide",
  },
  {
    id: "insurance-pro-guide",
    title: "Insurance Professional Guide",
    category: "Partner Guides",
    tags: ["insurance", "professional", "guide", "placement"],
    summary: "Guide for insurance professionals on PPVA placement — compensation, process, and case management.",
    type: "guide",
  },
  {
    id: "opportunity-brief",
    title: "Advantage/Axcelus Opportunity Brief",
    category: "Partner Guides",
    tags: ["advantage", "axcelus", "opportunity", "pitch"],
    summary: "Master opportunity brief for the Advantage and Axcelus PPLI/PPVA platform.",
    sourceFile: "docs/Ppli_ppva Master — Advantage_axcelus Opportunity Brief (3).docx",
    type: "document",
  },
  // Process Documents
  {
    id: "workflow-narrative",
    title: "Policy Placement Workflow Narrative",
    category: "Process Documents",
    tags: ["workflow", "narrative", "process", "phases"],
    summary: "Complete 4-phase process architecture with detailed narrative for each phase and transition rules.",
    sourceFile: "docs/Policy_Placement_Workflow_Narrative_Guide.md",
    type: "document",
  },
  {
    id: "15-step-task-list",
    title: "Detailed 15-Step Task List",
    category: "Process Documents",
    tags: ["15-step", "task", "execution", "roadmap"],
    summary: "Execution roadmap with all 15 steps, owners, prerequisites, documents, and timing for each.",
    sourceFile: "docs/Detailed_15_Step_Task_List.md",
    type: "document",
  },
  {
    id: "implementation-process",
    title: "PPLI Implementation Process",
    category: "Process Documents",
    tags: ["implementation", "process", "steps"],
    summary: "TPBC's PPLI implementation process document — step-by-step placement guide.",
    sourceFile: "docs/The Pacific Bridge Companies - PPLI Implementation Process.pdf",
    type: "pdf",
  },
  // Templates
  {
    id: "intake-form",
    title: "PPLI/PPVA Intake Form (Fillable)",
    category: "Templates",
    tags: ["intake", "form", "fillable", "client"],
    summary: "Fillable client intake form for PPLI/PPVA cases — captures all required information for case initiation.",
    sourceFile: "source-data/ppli-ppva-intake-2025-3-fillable.pdf",
    type: "template",
  },
  {
    id: "due-diligence",
    title: "VUL Due Diligence Document",
    category: "Templates",
    tags: ["due-diligence", "vul", "questionnaire"],
    summary: "Due diligence framework and questionnaire for variable universal life and private placement cases.",
    sourceFile: "docs/VUL Due Diligence Document (HM 06132025 1305 CST).pdf",
    type: "template",
  },
  // Fee Structures
  {
    id: "deal-model",
    title: "PPVA Deal Model — Master Build",
    category: "Fee Structures",
    tags: ["deal-model", "excel", "calculations", "master"],
    summary: "The canonical calculation engine. Contains all financial logic for premium waterfall, fund allocation, carrier illustration, and tax impact.",
    sourceFile: "source-data/PPVA_Deal_Model - Master Build.xlsx",
    type: "spreadsheet",
  },
  {
    id: "ohana-split",
    title: "Ohana Split Sheets",
    category: "Fee Structures",
    tags: ["ohana", "split", "compensation", "fees"],
    summary: "Fee sharing structure between PBWR and Ohana partners — commission splits and recurring revenue allocation.",
    sourceFile: "source-data/Ohana split.xlsx",
    type: "spreadsheet",
  },
  {
    id: "sou-fees",
    title: "Statement of Understanding — Fee Schedule",
    category: "Fee Structures",
    tags: ["sou", "fees", "3c", "oga", "advantage"],
    summary: "Official fee schedule for 3cStructures, OGA, and Advantage — premium loads, admin fees, and annual charges.",
    sourceFile: "source-data/Statement of Understanding. PPLI Onshore. 3c - OGA - Advantage.pdf",
    type: "pdf",
  },
  // Case Materials
  {
    id: "master-playbook",
    title: "TPBC PPVA Master Playbook (Phase 1)",
    category: "Case Materials",
    tags: ["playbook", "master", "tpbc", "phase1"],
    summary: "Master playbook document covering TPBC's PPVA platform, positioning, and operational framework.",
    sourceFile: "docs/TPBC_PPVA_Master_Playbook_Phase1.docx",
    type: "document",
  },
  {
    id: "impact-tool",
    title: "PPVA Impact Analysis Tool v10",
    category: "Case Materials",
    tags: ["impact", "analysis", "tool", "interactive"],
    summary: "Interactive HTML-based impact analysis tool showing PPVA vs current portfolio scenarios with multiple surrender designs.",
    sourceFile: "source-data/PPVA_Impact_Analysis_Tool_v10.html",
    type: "template",
  },
];
